export const ONBOARDING_CREATE_SELLER_START = 'ONBOARDING_CREATE_SELLER_START';
export const ONBOARDING_CREATE_SELLER_SUCCESS = 'ONBOARDING_CREATE_SELLER_SUCCESS';

export const ONBOARDING_SELLER_SET_DETAILS_SUCCESS = 'ONBOARDING_SELLER_SET_DETAILS_SUCCESS';
